### ISSUE TITLE
Changing server version

### ISSUE THREAD

**Issue by Faustyu1** [Eroxen/MC-Paint-datapack#5]
My minecraft server was running at 1.20.4 and used this datapack. I changing my Minecraft server version and version datapack, Also I changed the version in server.properties
When starting the server, it wrote You specified a resource pack without providing a sha1 hash. Pack will be updated on the client only if you change the name of the pack.resource-pack-id missing, using default of fdf17971-2346-3cb7-bff2-db358a289605. How do I get a hash for 1.20.6?

**Comment by Faustyu1** [comment]
And the player is trying to start drawing, but he writes, he has no rights. There is an essentialsx plugin and also writes to the console  [Essentials] CONSOLE issued server command: /tp @s ^
-1.029 ^.12 ^.211

**Comment by Eroxen** [comment]
Hey there! This page is meant for bugs in the datapack, if you want support for how to run the pack on your server the Discord would be a better place for that. Having said that, here are some things you can try:

For the resource pack, if you need the SHA1 hash you can try generating it with [this online tool](https://emn178.github.io/online-tools/sha1_checksum.html) or other similar tools.

For the Essentials error, I'm pretty sure this happens because the Essentials plugin changes the way that the `/tp` command works. You can try removing the plugin, but I've also heard from other people with similar issues that there is a way to remove certain commands from being changed by the plugin.

**Comment by Faustyu1** [comment]
https://github.com/user-attachments/assets/03ff9860-6e00-4a79-959d-1387b7e1beff

what a kill egg and what paint?

**Comment by Faustyu1** [comment]
![2024-08-07_14 09 57](https://github.com/user-attachments/assets/ddbea512-fef1-4cdb-aa05-e0ac7385d576)
and how can I kill the previous pictures
